# Generated by Django 5.2.2 on 2025-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='modelo',
        ),
        migrations.AddField(
            model_name='robot',
            name='bateria',
            field=models.IntegerField(db_column='T002Bateria', default=100),
        ),
        migrations.AddField(
            model_name='robot',
            name='nombre',
            field=models.CharField(db_column='T002Nombre', default='Robot sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='robot',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True, db_column='T002UltimaActividad'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En Mantenimiento', 'En Mantenimiento'), ('En Operación', 'En Operación'), ('Fuera de Servicio', 'Fuera de Servicio')], db_column='T002Estado', default='Disponible', max_length=50),
        ),
    ]
