# Generated by Django 5.2 on 2026-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_remove_robot_modelo_robot_bateria_robot_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ['nombre'], 'verbose_name': 'Robot Aspersor', 'verbose_name_plural': 'Robots Aspersores'},
        ),
        migrations.AddField(
            model_name='robot',
            name='finca',
            field=models.CharField(db_column='T002Finca', default='Finca La Riverita', editable=False, max_length=100, verbose_name='Finca asignada'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='nombre',
            field=models.CharField(db_column='T002Nombre', default='ASPERSAX-01', max_length=100, verbose_name='Nombre del robot aspersor'),
        ),
    ]
