# Generated by Django 5.2 on 2025-05-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malezas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malezadetectada',
            name='maleza',
            field=models.ForeignKey(db_column='T005IdMaleza', on_delete=django.db.models.deletion.CASCADE, related_name='maleza_detectada', to='malezas.maleza'),
        ),
    ]
