# Generated by Django 5.2.2 on 2025-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malezas', '0002_alter_malezadetectada_maleza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maleza',
            name='nombre_comun',
        ),
        migrations.AddField(
            model_name='maleza',
            name='nombre',
            field=models.CharField(db_column='T004Nombre', default='Maleza sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='maleza',
            name='resistencia_herbicida',
            field=models.BooleanField(db_column='T004ResistenciaHerbicida', default=False),
        ),
        migrations.AddField(
            model_name='maleza',
            name='temporada',
            field=models.CharField(blank=True, db_column='T004Temporada', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maleza',
            name='tipo',
            field=models.CharField(choices=[('Hoja Ancha', 'Hoja Ancha'), ('Hoja Angosta', 'Hoja Angosta'), ('Gramínea', 'Gramínea'), ('Otra', 'Otra')], db_column='T004Tipo', default='Otra', max_length=50),
        ),
        migrations.AlterField(
            model_name='maleza',
            name='nombre_cientifico',
            field=models.CharField(blank=True, db_column='T004NombreCientifico', max_length=200, null=True),
        ),
    ]
