# Generated by Django 5.2 on 2026-05-01 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malezas', '0003_remove_maleza_nombre_comun_maleza_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionTecnicaMaleza',
            fields=[
                ('id', models.AutoField(db_column='T007IdInfo', primary_key=True, serialize=False)),
                ('imagen_url', models.URLField(blank=True, db_column='T007ImagenUrl', max_length=500, null=True)),
                ('metodo_control', models.TextField(blank=True, db_column='T007MetodoControl', null=True)),
                ('quimico_recomendado', models.CharField(blank=True, db_column='T007QuimicoRecomendado', max_length=200, null=True)),
                ('nivel_peligro', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], db_column='T007NivelPeligro', default='Bajo', max_length=20)),
                ('maleza', models.OneToOneField(db_column='T007IdMaleza', on_delete=django.db.models.deletion.CASCADE, related_name='informacion_tecnica', to='malezas.maleza')),
            ],
            options={
                'verbose_name': 'Información Técnica de Maleza',
                'verbose_name_plural': 'Informaciones Técnicas de Malezas',
                'db_table': 'T007InformacionTecnica',
            },
        ),
    ]
