# Generated by Django 5.2 on 2026-05-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malezas', '0004_informaciontecnicamaleza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maleza',
            name='tipo',
        ),
        migrations.AddField(
            model_name='maleza',
            name='cantidad_romaza',
            field=models.IntegerField(db_column='T004Cantidad', default=0, verbose_name='Cantidad de Romaza'),
        ),
        migrations.AlterField(
            model_name='maleza',
            name='nombre',
            field=models.CharField(db_column='T004Nombre', default='Romaza', max_length=100),
        ),
    ]
