# Generated by Django 5.2 on 2026-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malezas', '0005_remove_maleza_tipo_maleza_cantidad_romaza_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maleza',
            options={'ordering': ['-id_maleza'], 'verbose_name': 'Registro de Romaza', 'verbose_name_plural': 'Registros de Romaza'},
        ),
        migrations.AddField(
            model_name='maleza',
            name='finca',
            field=models.CharField(db_column='T004Finca', default='Finca La Riverita', editable=False, max_length=100, verbose_name='Finca'),
        ),
        migrations.AlterField(
            model_name='maleza',
            name='cantidad_romaza',
            field=models.IntegerField(db_column='T004Cantidad', default=0, verbose_name='Cantidad de plantas Romaza detectadas'),
        ),
        migrations.AlterField(
            model_name='maleza',
            name='descripcion',
            field=models.TextField(blank=True, db_column='T004Descripcion', null=True, verbose_name='Observaciones del área'),
        ),
        migrations.AlterField(
            model_name='maleza',
            name='nombre',
            field=models.CharField(db_column='T004Nombre', help_text='Nombre del lote o sector de la Finca La Riverita (ej: Lote 1, Sector Norte)', max_length=100, verbose_name='Área de Trabajo'),
        ),
        migrations.AlterField(
            model_name='maleza',
            name='nombre_cientifico',
            field=models.CharField(blank=True, db_column='T004NombreCientifico', default='Rumex crispus', max_length=200, null=True, verbose_name='Nombre Científico de la Maleza'),
        ),
        migrations.AlterField(
            model_name='maleza',
            name='resistencia_herbicida',
            field=models.BooleanField(db_column='T004ResistenciaHerbicida', default=False, verbose_name='¿Romaza resistente al herbicida?'),
        ),
        migrations.AlterField(
            model_name='maleza',
            name='temporada',
            field=models.CharField(blank=True, db_column='T004Temporada', max_length=100, null=True, verbose_name='Temporada de detección'),
        ),
    ]
