<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-07 02:28
=======
# Generated by Django 5.2 on 2025-08-17 20:40
>>>>>>> 30311b5 (Primer commit: API Aspersax)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maleza',
            fields=[
                ('id_maleza', models.AutoField(db_column='T004IdMaleza', editable=False, primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('nombre_comun', models.CharField(db_column='T004NombreComun', max_length=100)),
                ('nombre_cientifico', models.CharField(blank=True, db_column='T004NombreCientifico', max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='T004Descripcion', null=True)),
=======
                ('nombre', models.CharField(db_column='T004Nombre', default='Maleza sin nombre', max_length=100)),
                ('nombre_cientifico', models.CharField(blank=True, db_column='T004NombreCientifico', max_length=200, null=True)),
                ('tipo', models.CharField(choices=[('Hoja Ancha', 'Hoja Ancha'), ('Hoja Angosta', 'Hoja Angosta'), ('Gramínea', 'Gramínea'), ('Otra', 'Otra')], db_column='T004Tipo', default='Otra', max_length=50)),
                ('descripcion', models.TextField(blank=True, db_column='T004Descripcion', null=True)),
                ('temporada', models.CharField(blank=True, db_column='T004Temporada', max_length=100, null=True)),
                ('resistencia_herbicida', models.BooleanField(db_column='T004ResistenciaHerbicida', default=False)),
>>>>>>> 30311b5 (Primer commit: API Aspersax)
                ('activo', models.BooleanField(db_column='T004Activo', default=True)),
            ],
            options={
                'verbose_name': 'Maleza',
                'verbose_name_plural': 'Malezas',
                'db_table': 'T004Maleza',
            },
        ),
        migrations.CreateModel(
            name='MalezaDetectada',
            fields=[
                ('id', models.AutoField(db_column='T005IdMalezaDetectada', editable=False, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(db_column='T005Ubicacion', max_length=200)),
                ('densidad', models.CharField(db_column='T005Densidad', max_length=50)),
                ('activo', models.BooleanField(db_column='T005Activo', default=True)),
                ('jornada', models.ForeignKey(db_column='T005IdJornada', on_delete=django.db.models.deletion.CASCADE, related_name='malezas_detectadas', to='jornadas.jornada')),
<<<<<<< HEAD
                ('maleza', models.ForeignKey(db_column='T005IdMaleza', on_delete=django.db.models.deletion.CASCADE, to='malezas.maleza')),
=======
                ('maleza', models.ForeignKey(db_column='T005IdMaleza', on_delete=django.db.models.deletion.CASCADE, related_name='maleza_detectada', to='malezas.maleza')),
>>>>>>> 30311b5 (Primer commit: API Aspersax)
            ],
            options={
                'verbose_name': 'Maleza Detectada',
                'verbose_name_plural': 'Malezas Detectadas',
                'db_table': 'T005MalezaDetectada',
            },
        ),
    ]
