<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-07 02:11
=======
# Generated by Django 5.2 on 2025-08-17 20:40
>>>>>>> 30311b5 (Primer commit: API Aspersax)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id_robot', models.AutoField(db_column='T002IdRobot', editable=False, primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('modelo', models.CharField(db_column='T002Modelo', max_length=100)),
                ('estado', models.CharField(db_column='T002Estado', max_length=50)),
=======
                ('nombre', models.CharField(db_column='T002Nombre', default='Robot sin nombre', max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Mantenimiento', 'En Mantenimiento'), ('En Operación', 'En Operación'), ('Fuera de Servicio', 'Fuera de Servicio')], db_column='T002Estado', default='Disponible', max_length=50)),
                ('bateria', models.IntegerField(db_column='T002Bateria', default=100)),
                ('ultima_actividad', models.DateTimeField(auto_now=True, db_column='T002UltimaActividad')),
>>>>>>> 30311b5 (Primer commit: API Aspersax)
                ('activo', models.BooleanField(db_column='T002Activo', default=True)),
            ],
            options={
                'verbose_name': 'Robot',
                'verbose_name_plural': 'Robots',
                'db_table': 'T002Robot',
            },
        ),
    ]
