# Generated by Django 5.2 on 2025-04-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id_robot', models.AutoField(db_column='T002IdRobot', editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(db_column='T002Modelo', max_length=100)),
                ('estado', models.CharField(db_column='T002Estado', max_length=50)),
                ('activo', models.BooleanField(db_column='T002Activo', default=True)),
            ],
            options={
                'verbose_name': 'Robot',
                'verbose_name_plural': 'Robots',
                'db_table': 'T002Robot',
            },
        ),
    ]
