# Generated by Django 5.2 on 2025-04-07 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maleza',
            fields=[
                ('id_maleza', models.AutoField(db_column='T004IdMaleza', editable=False, primary_key=True, serialize=False)),
                ('nombre_comun', models.CharField(db_column='T004NombreComun', max_length=100)),
                ('nombre_cientifico', models.CharField(blank=True, db_column='T004NombreCientifico', max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='T004Descripcion', null=True)),
                ('activo', models.BooleanField(db_column='T004Activo', default=True)),
            ],
            options={
                'verbose_name': 'Maleza',
                'verbose_name_plural': 'Malezas',
                'db_table': 'T004Maleza',
            },
        ),
        migrations.CreateModel(
            name='MalezaDetectada',
            fields=[
                ('id', models.AutoField(db_column='T005IdMalezaDetectada', editable=False, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(db_column='T005Ubicacion', max_length=200)),
                ('densidad', models.CharField(db_column='T005Densidad', max_length=50)),
                ('activo', models.BooleanField(db_column='T005Activo', default=True)),
                ('jornada', models.ForeignKey(db_column='T005IdJornada', on_delete=django.db.models.deletion.CASCADE, related_name='malezas_detectadas', to='jornadas.jornada')),
                ('maleza', models.ForeignKey(db_column='T005IdMaleza', on_delete=django.db.models.deletion.CASCADE, to='malezas.maleza')),
            ],
            options={
                'verbose_name': 'Maleza Detectada',
                'verbose_name_plural': 'Malezas Detectadas',
                'db_table': 'T005MalezaDetectada',
            },
        ),
    ]
