# Generated by Django 5.2 on 2025-04-07 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        ('tanques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(db_column='T001IdJornada', editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='T001Fecha')),
                ('hora_inicio', models.TimeField(db_column='T001HoraInicio')),
                ('hora_fin', models.TimeField(db_column='T001HoraFin')),
                ('duracion', models.DurationField(db_column='T001Duracion')),
                ('area_tratada', models.FloatField(db_column='T001AreaTratada')),
                ('activo', models.BooleanField(db_column='T001Activo', default=True)),
                ('robot', models.ForeignKey(db_column='T001Robot', on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
                ('tanque', models.ForeignKey(db_column='T001Tanque', on_delete=django.db.models.deletion.CASCADE, to='tanques.tanque')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'T001Jornada',
            },
        ),
    ]
