# Generated by Django 5.2 on 2026-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['-fecha'], 'verbose_name': 'Jornada de Aspersión', 'verbose_name_plural': 'Jornadas de Aspersión'},
        ),
        migrations.AddField(
            model_name='jornada',
            name='finca',
            field=models.CharField(db_column='T001Finca', default='Finca La Riverita', editable=False, max_length=100, verbose_name='Finca'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='area_tratada',
            field=models.FloatField(db_column='T001AreaTratada', verbose_name='Área tratada en Finca La Riverita (ha)'),
        ),
    ]
