# Generated by Django 5.2 on 2025-04-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='T006IdReporte', editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='T006FechaCreacion')),
                ('resumen', models.TextField(blank=True, db_column='T006Resumen')),
                ('activo', models.BooleanField(db_column='T006Activo', default=True)),
                ('jornada', models.OneToOneField(db_column='T006IdJornada', on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='jornadas.jornada')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'T006Reporte',
            },
        ),
    ]
