<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-07 02:37

import django.db.models.deletion
=======
# Generated by Django 5.2 on 2025-08-17 20:40

import datetime
import django.db.models.deletion
import django.utils.timezone
>>>>>>> 30311b5 (Primer commit: API Aspersax)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('jornadas', '0001_initial'),
=======
        ('malezas', '0001_initial'),
        ('robots', '0001_initial'),
        ('tanques', '0001_initial'),
>>>>>>> 30311b5 (Primer commit: API Aspersax)
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='T006IdReporte', editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='T006FechaCreacion')),
                ('resumen', models.TextField(blank=True, db_column='T006Resumen')),
                ('activo', models.BooleanField(db_column='T006Activo', default=True)),
                ('jornada', models.OneToOneField(db_column='T006IdJornada', on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='jornadas.jornada')),
=======
            name='DetalleMaleza',
            fields=[
                ('id_detalle', models.AutoField(db_column='T006IdDetalle', editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='T006Cantidad', default=1)),
                ('ubicacion', models.CharField(blank=True, db_column='T006Ubicacion', max_length=200, null=True)),
                ('herbicida_aplicado', models.FloatField(db_column='T006HerbicidaAplicado', default=0)),
                ('efectividad', models.IntegerField(db_column='T006Efectividad', default=0)),
                ('maleza', models.ForeignKey(db_column='T006IdMaleza', on_delete=django.db.models.deletion.CASCADE, to='malezas.maleza')),
            ],
            options={
                'verbose_name': 'Detalle de Maleza',
                'verbose_name_plural': 'Detalles de Malezas',
                'db_table': 'T006DetalleMaleza',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='T005IdReporte', editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='T005Fecha', default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Jornada', 'Jornada'), ('Mantenimiento', 'Mantenimiento'), ('Incidente', 'Incidente'), ('Recarga', 'Recarga')], db_column='T005Tipo', default='Jornada', max_length=50)),
                ('area_cubierta', models.FloatField(db_column='T005AreaCubierta', default=0)),
                ('herbicida_usado', models.FloatField(db_column='T005HerbicidaUsado', default=0)),
                ('duracion', models.DurationField(db_column='T005Duracion', default=datetime.timedelta(0))),
                ('observaciones', models.TextField(blank=True, db_column='T005Observaciones', null=True)),
                ('activo', models.BooleanField(db_column='T005Activo', default=True)),
                ('malezas_detectadas', models.ManyToManyField(db_column='T005MalezasDetectadas', through='reportes.DetalleMaleza', to='malezas.maleza')),
                ('robot', models.ForeignKey(db_column='T005IdRobot', null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.robot')),
                ('tanque', models.ForeignKey(blank=True, db_column='T005IdTanque', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tanques.tanque')),
>>>>>>> 30311b5 (Primer commit: API Aspersax)
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
<<<<<<< HEAD
                'db_table': 'T006Reporte',
            },
        ),
=======
                'db_table': 'T005Reporte',
            },
        ),
        migrations.AddField(
            model_name='detallemaleza',
            name='reporte',
            field=models.ForeignKey(db_column='T006IdReporte', on_delete=django.db.models.deletion.CASCADE, to='reportes.reporte'),
        ),
>>>>>>> 30311b5 (Primer commit: API Aspersax)
    ]
