# Generated by Django 5.2.2 on 2025-06-05 19:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malezas', '0003_remove_maleza_nombre_comun_maleza_nombre_and_more'),
        ('reportes', '0001_initial'),
        ('robots', '0002_remove_robot_modelo_robot_bateria_robot_nombre_and_more'),
        ('tanques', '0003_remove_tanque_tipo_tanque_nivel_actual_tanque_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='resumen',
        ),
        migrations.AddField(
            model_name='reporte',
            name='area_cubierta',
            field=models.FloatField(db_column='T005AreaCubierta', default=0),
        ),
        migrations.AddField(
            model_name='reporte',
            name='duracion',
            field=models.DurationField(db_column='T005Duracion', default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(db_column='T005Fecha', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reporte',
            name='herbicida_usado',
            field=models.FloatField(db_column='T005HerbicidaUsado', default=0),
        ),
        migrations.AddField(
            model_name='reporte',
            name='observaciones',
            field=models.TextField(blank=True, db_column='T005Observaciones', null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='robot',
            field=models.ForeignKey(db_column='T005IdRobot', null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.robot'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tanque',
            field=models.ForeignKey(blank=True, db_column='T005IdTanque', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tanques.tanque'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('Jornada', 'Jornada'), ('Mantenimiento', 'Mantenimiento'), ('Incidente', 'Incidente'), ('Recarga', 'Recarga')], db_column='T005Tipo', default='Jornada', max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='activo',
            field=models.BooleanField(db_column='T005Activo', default=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='id_reporte',
            field=models.AutoField(db_column='T005IdReporte', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='reporte',
            table='T005Reporte',
        ),
        migrations.CreateModel(
            name='DetalleMaleza',
            fields=[
                ('id_detalle', models.AutoField(db_column='T006IdDetalle', editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='T006Cantidad', default=1)),
                ('ubicacion', models.CharField(blank=True, db_column='T006Ubicacion', max_length=200, null=True)),
                ('herbicida_aplicado', models.FloatField(db_column='T006HerbicidaAplicado', default=0)),
                ('efectividad', models.IntegerField(db_column='T006Efectividad', default=0)),
                ('maleza', models.ForeignKey(db_column='T006IdMaleza', on_delete=django.db.models.deletion.CASCADE, to='malezas.maleza')),
                ('reporte', models.ForeignKey(db_column='T006IdReporte', on_delete=django.db.models.deletion.CASCADE, to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Detalle de Maleza',
                'verbose_name_plural': 'Detalles de Malezas',
                'db_table': 'T006DetalleMaleza',
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='malezas_detectadas',
            field=models.ManyToManyField(db_column='T005MalezasDetectadas', through='reportes.DetalleMaleza', to='malezas.maleza'),
        ),
    ]
