# Generated by Django 5.2 on 2025-04-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id_tanque', models.AutoField(db_column='T001IdTanque', editable=False, primary_key=True, serialize=False)),
                ('capacidad', models.DecimalField(db_column='T001Capacidad', decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(db_column='T001Tipo', max_length=50)),
                ('estado', models.CharField(db_column='T001Estado', max_length=50)),
                ('activo', models.BooleanField(db_column='T001Activo', default=True)),
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
                'db_table': 'T001Tanque',
            },
        ),
    ]
