# Generated by Django 5.2 on 2025-04-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='activo',
            field=models.BooleanField(db_column='T003Activo', default=True),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='capacidad',
            field=models.DecimalField(db_column='T003Capacidad', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='estado',
            field=models.CharField(db_column='T003Estado', max_length=50),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='id_tanque',
            field=models.AutoField(db_column='T003IdTanque', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='tipo',
            field=models.CharField(db_column='T003Tipo', max_length=50),
        ),
        migrations.AlterModelTable(
            name='tanque',
            table='T003Tanque',
        ),
    ]
