# Generated by Django 5.2.2 on 2025-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanques', '0002_alter_tanque_activo_alter_tanque_capacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanque',
            name='tipo',
        ),
        migrations.AddField(
            model_name='tanque',
            name='nivel_actual',
            field=models.FloatField(db_column='T003NivelActual', default=0),
        ),
        migrations.AddField(
            model_name='tanque',
            name='nombre',
            field=models.CharField(db_column='T003Nombre', default='Tanque sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='tanque',
            name='ultima_recarga',
            field=models.DateTimeField(auto_now=True, db_column='T003UltimaRecarga'),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='capacidad',
            field=models.FloatField(db_column='T003Capacidad', default=0),
        ),
        migrations.AlterField(
            model_name='tanque',
            name='estado',
            field=models.CharField(choices=[('Lleno', 'Lleno'), ('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Vacío', 'Vacío')], db_column='T003Estado', default='Vacío', max_length=50),
        ),
    ]
