<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-07 02:12
=======
# Generated by Django 5.2 on 2025-08-17 20:40
>>>>>>> 30311b5 (Primer commit: API Aspersax)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
<<<<<<< HEAD
                ('id_tanque', models.AutoField(db_column='T001IdTanque', editable=False, primary_key=True, serialize=False)),
                ('capacidad', models.DecimalField(db_column='T001Capacidad', decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(db_column='T001Tipo', max_length=50)),
                ('estado', models.CharField(db_column='T001Estado', max_length=50)),
                ('activo', models.BooleanField(db_column='T001Activo', default=True)),
=======
                ('id_tanque', models.AutoField(db_column='T003IdTanque', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T003Nombre', default='Tanque sin nombre', max_length=100)),
                ('capacidad', models.FloatField(db_column='T003Capacidad', default=0)),
                ('nivel_actual', models.FloatField(db_column='T003NivelActual', default=0)),
                ('estado', models.CharField(choices=[('Lleno', 'Lleno'), ('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Vacío', 'Vacío')], db_column='T003Estado', default='Vacío', max_length=50)),
                ('ultima_recarga', models.DateTimeField(auto_now=True, db_column='T003UltimaRecarga')),
                ('activo', models.BooleanField(db_column='T003Activo', default=True)),
>>>>>>> 30311b5 (Primer commit: API Aspersax)
            ],
            options={
                'verbose_name': 'Tanque',
                'verbose_name_plural': 'Tanques',
<<<<<<< HEAD
                'db_table': 'T001Tanque',
=======
                'db_table': 'T003Tanque',
>>>>>>> 30311b5 (Primer commit: API Aspersax)
            },
        ),
    ]
